### ISSUE TITLE
Error occurred when making dirs

### ISSUE THREAD

**Issue by tagucci** [UKPLab/lrec2018-live-blog-corpus#1]
Hi, thanks for a nice repo of summarization dataset!
When I run the command `python generate_data.py --corpus=guardian --mode=download --data_type=processed` with python 2.7.6, I encountered a following error.
```
Traceback (most recent call last):
  File "generate_data.py", line 498, in <module>
    main()
  File "generate_data.py", line 492, in main
    mkdirp(path)
  File "generate_data.py", line 37, in mkdirp
    os.makedirs(path)
  File "/Users/tagucci/.pyenv/versions/py2.7/lib/python2.7/os.py", line 145, in makedirs
    head, tail = path.split(name)
  File "/Users/tagucci/.pyenv/versions/py2.7/lib/python2.7/posixpath.py", line 92, in split
    i = p.rfind('/') + 1
AttributeError: 'module' object has no attribute 'rfind'
```
How can I solve this error?

**Comment by avineshpvs** [comment]
Thanks for pointing. I fixed it.
